version: "3"

services:
  ingress:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./nginx.conf.d:/etc/nginx/conf.d"

  inlets:
    image: inlets/inlets:2.6.4
    command: server --token ${INLETS_TOKEN}

  mysql:
    image: mysql:5.6 
    networks:
    - system_default
    ports:
      - "3306:3306"
    volumes:
      - "/data/mysql:/var/lib/mysql"

networks:  
  system_default:
    external: true